AWSTemplateFormatVersion: '2010-09-09'
Description: "This templates is to create a Lambda-backed Custom Resource"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'Inputs for Lambda Layer'
        Parameters:
          - S3BucketName
          - LayerPackage
      - Label:
          default: 'Inputs for Lambda Function'
        Parameters:
          - FunctionName
          - MethodName
          - ModuleName
      - Label:
          default: 'Inputs for Custom Resource'
        Parameters:
          - Length

Parameters:
  S3BucketName:
    Description: 'S3 Bucket hosting the packages for Lambda Layer'
    Type: String
  LayerPackage:
    Description: 'Name of package zip file containing the modules for Lambda'
    Type: String
    Default: 'layers.zip'
  FunctionName:
    Type: String
    Default: 'testfunction'
  MethodName:
    Description: 'Method name that will be executed by Lambda'
    Type: String
    Default: 'lambda_handler'
  ModuleName:
    Description: 'Using ZipFile will generate index.py file'
    Type: String
    Default: 'index'
  Length:
    Description: 'Input parameter for Custom Resource'
    Type: Number
    Default: 10

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: CustomResourceLambdaExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - ec2:DescribeImages
            Resource: "*"

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: customResourcePkgs
      Description: Dependencies for the utility function
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref LayerPackage
      CompatibleRuntimes:
        - python3.9  

  LambdaTestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: 'Test Function to visualize Input Output'
      Runtime: python3.9
      FunctionName: !Ref FunctionName
      Role: !GetAtt LambdaExecutionRole.Arn
      # Have to name it Python_File_Name.Method_Name
      Handler: !Sub '${ModuleName}.${MethodName}'      
      Layers:
        - !Ref LambdaLayer
      Code:
        ZipFile: |
          import json
          import random, string
          import cfnresponse

          def generate_random_string(length):
              characters = string.ascii_letters + string.digits + string.punctuation
              random_string = ''.join(random.choice(characters) for index in range(length))
              return random_string

          def lambda_handler(event, context):
              try:
                
                # To see the responseData
                ## Note this will be printed in CloudWatch Logs
                responseData = {
                    'statusCode': 200,
                    'body': json.dumps(event)
                }

                string_length = int(event["ResourceProperties"]["Length"])
                final_output = str(generate_random_string(string_length))

                
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, final_output)
              except Exception as err:
                print(f'{err}')
                cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
  
  GetRandomString:
    Type: Custom::LambdaTestFunction
    Properties:
      ServiceToken: !GetAtt LambdaTestFunction.Arn
      Region: !Ref "AWS::Region"
      Length: !Ref Length

Outputs:
  GetRandomString:
    Value: !Ref GetRandomString