AWSTemplateFormatVersion: '2010-09-09'
Description: "Understanding APIGateway Setup and use of lambda backed resources"

# test-apigateway-autodeploy-stack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "REST API JSON File and S3 Bucket"
        Parameters:
          - APIJsonS3Bucket
          - APIJsonS3BucketArn
          - RestApiFilename
          - RestApiFileVersion
          
      - Label:
          default: "ApiGateway Configuration"
        Parameters:
          - EndpointConfigurationType

Parameters:

  APIJsonS3Bucket:
    Type: String
    Description: "S3 Bucket name containing the REST API JSON file"

  APIJsonS3BucketArn:
    Type: String
    Description: "ARN of S3 Bucket"

  RestApiFilename:
    Type: String
    Description: "Name of REST API JSON file"

  RestApiFileVersion:
    Type: String
    Description: "Version ID of REST API JSON file in S3 Bucket"

  # Used to indicate the new version ID
  RestApiFileVersionNext:
    Type: String
    Description: "Next Version ID of REST API JSON file in S3 Bucket"

  EndpointConfigurationType:
    Type: String
    Description: "A list of endpoint types of an API or custome domain name"

    AllowedValues:
      - "EDGE"
      - "REGIONAL"
      - "PRIVATE"

Conditions:
  CreatePolicy: !Equals [!Ref EndpointConfigurationType, 'PRIVATE']

Resources:
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "My ApiGateway"
      Description: "Test API Gateway, deploy with CF"
      BodyS3Location:
        Bucket: !Sub "${APIJsonS3Bucket}"
        Key: !Sub "${RestApiFilename}"
        Version: !Sub "${RestApiFileVersion}"
      EndpointConfiguration:
        Types:
          - !Sub "${EndpointConfigurationType}"
      Policy:
        !If 
        - CreatePolicy
        -
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: '*'
        - !Ref "AWS::NoValue"

  DevDeploymentNoStage:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MyApiGateway
      Description: !Sub "dev stage deployment for API file, version id ${RestApiFileVersion}"

  DevDeploymentNoStageNext:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MyApiGateway
      Description: !Sub "dev stage deployment for API file, version id ${RestApiFileVersionNext}"

  DevStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: dev
      RestApiId: !Ref MyApiGateway
      DeploymentId: !Ref DevDeploymentNoStageNext
      Variables:
        Name: DevStage

Outputs:
  CheckDeploymentNoStage:
    Value: !Ref DevDeploymentNoStage
  CheckDeploymentNoStageNext:
    Value: !Ref DevDeploymentNoStageNext    